In [3]:
import nltk
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('stopwords')
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from nltk.tokenize import WhitespaceTokenizer
from gensim.models import Word2Vec
import numpy as np
nltk.download('punkt')

# Sample data
corpus = ["Natural Language Processing is amazing!",
          "Text data requires cleaning and processing.",
          "Tokenization and vectorization help with NLP tasks."]

# Bag of Words
vectorizer = CountVectorizer()
bow_matrix = vectorizer.fit_transform(corpus)
print("Bag-of-Words (Count Occurrence):")
print(bow_matrix.toarray())

# Normalized Count Occurrence
bow_matrix_norm = bow_matrix.toarray() / np.linalg.norm(bow_matrix.toarray(), axis=1, keepdims=True)
print("\nNormalized BoW:")
print(bow_matrix_norm)

# TF-IDF
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(corpus)
print("\nTF-IDF:")
print(tfidf_matrix.toarray())

# Word2Vec Embedding
tokenized_corpus = [WhitespaceTokenizer().tokenize(sentence.lower()) for sentence in corpus]
word2vec_model = Word2Vec(sentences=tokenized_corpus, vector_size=50, window=3, min_count=1, workers=4)
print("\nWord2Vec Example:")
print(word2vec_model.wv["nlp"])  # Example word vector


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


Bag-of-Words (Count Occurrence):
[[1 0 0 0 0 1 1 1 0 1 0 0 0 0 0 0]
 [0 1 1 1 0 0 0 0 0 1 1 0 1 0 0 0]
 [0 1 0 0 1 0 0 0 1 0 0 1 0 1 1 1]]

Normalized BoW:
[[0.4472136  0.         0.         0.         0.         0.4472136
  0.4472136  0.4472136  0.         0.4472136  0.         0.
  0.         0.         0.         0.        ]
 [0.         0.40824829 0.40824829 0.40824829 0.         0.
  0.         0.         0.         0.40824829 0.40824829 0.
  0.40824829 0.         0.         0.        ]
 [0.         0.37796447 0.         0.         0.37796447 0.
  0.         0.         0.37796447 0.         0.         0.37796447
  0.         0.37796447 0.37796447 0.37796447]]

TF-IDF:
[[0.46735098 0.         0.         0.         0.         0.46735098
  0.46735098 0.46735098 0.         0.35543247 0.         0.
  0.         0.         0.         0.        ]
 [0.         0.3349067  0.44036207 0.44036207 0.         0.
  0.         0.         0.         0.3349067  0.44036207 0.
  0.44036207 0.        